import { z } from 'zod'

const code = z.string().trim().min(1, 'Mã là bắt buộc.').max(100, 'Mã quá dài.').regex(/^[A-Za-z][A-Za-z0-9_]*$/, 'Chỉ dùng chữ, số và dấu gạch dưới; ký tự đầu phải là chữ.')
const currency = z.string().trim().length(3, 'Currency phải gồm 3 ký tự.').regex(/^[A-Za-z]{3}$/, 'Currency phải là 3 chữ cái.')

export const featureSchema = z.object({ code, name: z.string().trim().min(1, 'Tên là bắt buộc.').max(150, 'Tên quá dài.'), description: z.string() })
export const featureUpdateSchema = featureSchema.pick({ name: true, description: true }).extend({ active: z.boolean() })
export const packageSchema = z.object({ code: code.max(50, 'Mã package quá dài.'), name: z.string().trim().min(1, 'Tên là bắt buộc.').max(100, 'Tên quá dài.'), description: z.string(), priceAmount: z.string().min(1, 'Giá là bắt buộc.').refine((value) => Number.isFinite(Number(value)) && Number(value) >= 0, 'Giá phải là số không âm.'), currencyCode: currency, billingCycleMonths: z.string().refine((value) => Number.isInteger(Number(value)) && Number(value) >= 1 && Number(value) <= 120, 'Chu kỳ phải từ 1 đến 120 tháng.') })
export const packageUpdateSchema = packageSchema.omit({ code: true })
export const subscriptionSchema = z.object({ restaurantId: z.string().trim().uuid('Restaurant ID phải là UUID hợp lệ.'), packageCode: z.string().min(1, 'Hãy chọn package.'), startAt: z.string().min(1, 'Thời gian bắt đầu là bắt buộc.'), endAt: z.string().min(1, 'Thời gian kết thúc là bắt buộc.'), autoRenew: z.boolean(), priceAmount: z.string().min(1, 'Giá là bắt buộc.').refine((value) => Number.isFinite(Number(value)) && Number(value) >= 0, 'Giá phải là số không âm.'), currencyCode: currency }).superRefine((value, context) => { if (value.startAt && value.endAt && new Date(value.endAt) <= new Date(value.startAt)) context.addIssue({ code: 'custom', path: ['endAt'], message: 'Thời gian kết thúc phải sau bắt đầu.' }) })
export const changePackageSchema = z.object({ restaurantId: z.string().trim().uuid('Restaurant ID phải là UUID hợp lệ.'), subscriptionId: z.string().trim().uuid('Subscription ID phải là UUID hợp lệ.'), packageCode: z.string().min(1, 'Hãy chọn package.'), endAt: z.string().min(1, 'Thời gian kết thúc là bắt buộc.'), autoRenew: z.boolean(), priceAmount: z.string().min(1, 'Giá là bắt buộc.').refine((value) => Number.isFinite(Number(value)) && Number(value) >= 0, 'Giá phải là số không âm.'), currencyCode: currency }).superRefine((value, context) => { if (value.endAt && new Date(value.endAt) <= new Date()) context.addIssue({ code: 'custom', path: ['endAt'], message: 'Thời gian kết thúc phải sau thời điểm hiện tại.' }) })
export const subscriptionIdentifiersSchema = z.object({ restaurantId: z.string().trim().uuid('Restaurant ID phải là UUID hợp lệ.'), subscriptionId: z.string().trim().uuid('Subscription ID phải là UUID hợp lệ.') })
export const featureFormSchema = featureSchema.extend({ active: z.boolean().optional() })
export const packageFormSchema = packageSchema.extend({ active: z.boolean().optional() })
export const restaurantStatusSchema = z.object({ status: z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED']), reason: z.string().trim().min(1, 'Reason là bắt buộc.').max(500, 'Reason quá dài.') })
export const restaurantListSchema = z.object({ q: z.string().max(100), status: z.enum(['', 'ACTIVE', 'INACTIVE', 'SUSPENDED']), page: z.number().int().min(0), size: z.number().int().min(1).max(100), sortBy: z.enum(['createdAt', 'updatedAt', 'code', 'name', 'status']), direction: z.enum(['asc', 'desc']) })
export const subscriptionListSchema = z.object({ q: z.string(), restaurantId: z.string(), packageCode: z.string(), status: z.enum(['', 'PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED']), effective: z.enum(['', 'true', 'false']), page: z.number().int().min(0), size: z.number().int().min(1).max(100), sortBy: z.enum(['createdAt', 'startAt', 'endAt', 'status', 'priceAmount']), direction: z.enum(['asc', 'desc']) })
export const auditCriteriaSchema = z.object({ scope: z.enum(['ALL', 'SYSTEM', 'TENANT']), restaurantId: z.string(), actorUserId: z.string(), actionCode: z.string(), entityType: z.string(), entityId: z.string(), from: z.string(), to: z.string(), page: z.number().int().min(0), size: z.number().int().min(1).max(100) }).superRefine((value, context) => { if (value.from && Number.isNaN(new Date(value.from).getTime())) context.addIssue({ code: 'custom', path: ['from'], message: 'From phải là ISO Instant hợp lệ.' }); if (value.to && Number.isNaN(new Date(value.to).getTime())) context.addIssue({ code: 'custom', path: ['to'], message: 'To phải là ISO Instant hợp lệ.' }); if (value.from && value.to && new Date(value.to) <= new Date(value.from)) context.addIssue({ code: 'custom', path: ['to'], message: 'To phải sau From.' }); if (value.scope === 'SYSTEM' && value.restaurantId) context.addIssue({ code: 'custom', path: ['restaurantId'], message: 'Scope SYSTEM không được kết hợp restaurantId.' }) })
