import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { adminDashboardApi } from '../api/adminDashboardApi'
import { adminKeys } from '../api/adminKeys'
import { retryAdminQuery } from '../api/queryPolicy'
import { useAuthStore } from '../../auth/store/authStore'
import { EmptyState, ErrorState, LoadingSkeleton, PageHeader } from '../../../shared/components/AdminUi'
import { formatDateTime } from '../../../shared/utils/adminFormatting'

export function AdminDashboardPage() {
  const user = useAuthStore((state) => state.user)
  const canView = Boolean(user?.permissions.includes('ADMIN_DASHBOARD_VIEW'))
  const query = useQuery({ queryKey: adminKeys.dashboard.summary(), queryFn: adminDashboardApi.summary, retry: retryAdminQuery, enabled: canView })
  if (!canView) return <><PageHeader eyebrow="System overview" title="Admin dashboard" description="Dashboard yêu cầu permission ADMIN_DASHBOARD_VIEW." /><section className="card access-card"><EmptyState title="Chưa đủ quyền xem dashboard" description="Không gọi dashboard API và không hiển thị số 0 giả khi tài khoản thiếu permission." /></section></>
  return <><PageHeader eyebrow="System overview" title="Admin dashboard" description="Số liệu được lấy từ dashboard summary API. Revenue, MRR, ARR, churn và payment chưa có trong backend." />{query.isLoading ? <LoadingSkeleton rows={8} /> : query.isError ? <ErrorState error={query.error} onRetry={() => void query.refetch()} /> : !query.data ? <EmptyState title="Chưa có dữ liệu dashboard" description="Backend chưa trả về dashboard summary." /> : <DashboardContent summary={query.data} userPermissions={user?.permissions ?? []} />}</>
}

function DashboardContent({ summary, userPermissions }: { summary: Awaited<ReturnType<typeof adminDashboardApi.summary>>; userPermissions: string[] }) {
  const warnings = [{ label: 'Active không có subscription hiệu lực', value: summary.restaurants.activeWithoutEffectiveSubscription }, { label: 'Subscription stale active', value: summary.subscriptions.staleActive }, { label: 'Subscription sắp hết hạn trong 7 ngày', value: summary.subscriptions.expiringWithin7Days }].filter((item) => item.value > 0)
  return <><div className="dashboard-generated">Generated at: <strong title={summary.generatedAt}>{formatDateTime(summary.generatedAt)}</strong></div><div className="dashboard-section"><h3>Restaurants</h3><div className="stat-grid dashboard-stat-grid"><DashboardStat label="Tổng" value={summary.restaurants.total} /><DashboardStat label="Active" value={summary.restaurants.active} /><DashboardStat label="Inactive" value={summary.restaurants.inactive} /><DashboardStat label="Suspended" value={summary.restaurants.suspended} /><DashboardStat label="Mới 30 ngày" value={summary.restaurants.newLast30Days} /></div></div><div className="dashboard-section"><h3>Subscriptions</h3><div className="stat-grid dashboard-stat-grid"><DashboardStat label="Tổng" value={summary.subscriptions.total} /><DashboardStat label="Pending" value={summary.subscriptions.pending} /><DashboardStat label="Active status" value={summary.subscriptions.activeStatus} /><DashboardStat label="Effective now" value={summary.subscriptions.effectiveNow} /><DashboardStat label="Expired" value={summary.subscriptions.expired} /><DashboardStat label="Cancelled" value={summary.subscriptions.cancelled} /></div></div><div className="stat-grid"><DashboardStat label="Packages active / tổng" value={`${summary.packages.active} / ${summary.packages.total}`} /><DashboardStat label="Features active / tổng" value={`${summary.features.active} / ${summary.features.total}`} /></div>{warnings.length > 0 && <section className="warning-grid">{warnings.map((warning) => <div className="warning-card" key={warning.label}><span className="warning-symbol">!</span><div><strong>{warning.value}</strong><span>{warning.label}</span></div></div>)}</section>}<section className="card quick-actions"><div><div className="eyebrow">Quick actions</div><h3>Tiếp tục quản trị</h3></div><div className="quick-links">{userPermissions.includes('PACKAGE_MANAGE') && <Link to="/admin/features">+ Tạo feature</Link>}{userPermissions.includes('PACKAGE_MANAGE') && <Link to="/admin/packages">+ Tạo package</Link>}{userPermissions.includes('RESTAURANT_VIEW') && <Link to="/admin/restaurants">Restaurants →</Link>}{userPermissions.includes('SUBSCRIPTION_VIEW') && <Link to="/admin/subscriptions">Subscriptions →</Link>}{userPermissions.includes('AUDIT_VIEW') && <Link to="/admin/audit-logs">Audit logs →</Link>}</div></section></>
}

function DashboardStat({ label, value }: { label: string; value: number | string }) { return <div className="card dashboard-stat"><span className="eyebrow">{label}</span><strong>{value}</strong></div> }
