import { useState } from 'react'
import type { FormEventHandler } from 'react'
import { useForm, type FieldErrors, type FieldValues, type Path, type UseFormRegister, type UseFormRegisterReturn } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { packagesApi } from '../api/packagesApi'
import { restaurantsApi } from '../api/restaurantsApi'
import { adminSubscriptionsApi } from '../api/adminSubscriptionsApi'
import { adminKeys } from '../api/adminKeys'
import { retryAdminQuery } from '../api/queryPolicy'
import { changePackageSchema, subscriptionIdentifiersSchema, subscriptionSchema } from '../schemas'
import { useAuthStore } from '../../auth/store/authStore'
import { normalizeApiError } from '../../../shared/errors/normalizeApiError'
import type { AdminPackageResponse, SubscriptionResponse } from '../../../shared/types/admin'
import { EmptyState, ErrorState, FieldError, LoadingSkeleton, PageHeader, Toast } from '../../../shared/components/AdminUi'
import { formatDateTime, formatMoney, toDateTimeLocal, toUtcIso } from '../../../shared/utils/adminFormatting'
import { canManageRestaurantSubscriptions } from '../utils/subscriptionWorkflow'

type Operation = 'activate' | 'change' | 'cancel'

export function SubscriptionPage() {
  const queryClient = useQueryClient()
  const canManage = canManageRestaurantSubscriptions(useAuthStore((state) => state.user))
  const packagesQuery = useQuery({ queryKey: adminKeys.packages(false), queryFn: () => packagesApi.list(false), retry: retryAdminQuery, enabled: canManage })
  const [operation, setOperation] = useState<Operation>('activate')
  const [result, setResult] = useState<SubscriptionResponse | null>(null)
  const [toast, setToast] = useState<{ message: string; tone: 'success' | 'error' } | null>(null)
  const notifyError = (error: unknown) => { const normalized = normalizeApiError(error); if (normalized.status === 409) void Promise.all([queryClient.invalidateQueries({ queryKey: ['admin', 'restaurants'] }), queryClient.invalidateQueries({ queryKey: ['admin', 'subscriptions'] }), queryClient.invalidateQueries({ queryKey: adminKeys.dashboard.all })]); setToast({ message: normalized.message, tone: 'error' }) }
  const handleResult = (response: SubscriptionResponse) => { setResult(response); void invalidateSubscriptionQueries(queryClient, response) }
  return <>
    <PageHeader eyebrow="Operations / Subscriptions" title="Subscription operations" description="Thực hiện thao tác trên subscription khi đã biết chính xác UUID nhà hàng và subscription." />
    {toast && <Toast message={toast.message} tone={toast.tone} />}
    <div className="info-banner"><strong>Thao tác subscription yêu cầu UUID chính xác.</strong><span>Có thể lấy restaurant ID và subscription ID từ các màn hình danh sách/detail. Kết quả sau mutation được hiển thị lại từ response của backend.</span></div>
    <div className="subscription-grid"><section className="card detail-card"><div className="section-heading"><div><div className="eyebrow">New subscription</div><h3>Tạo subscription PENDING</h3></div></div>{!canManage ? <EmptyState title="Không đủ quyền" description="Cần SUBSCRIPTION_MANAGE để thực hiện thao tác subscription." /> : packagesQuery.isLoading ? <LoadingSkeleton rows={4} /> : packagesQuery.isError ? <ErrorState error={packagesQuery.error} onRetry={() => void packagesQuery.refetch()} /> : <CreateSubscriptionForm packages={packagesQuery.data ?? []} onSuccess={(response) => { handleResult(response); setToast({ message: 'Đã tạo subscription PENDING.', tone: 'success' }) }} onError={notifyError} />}</section><section className="card detail-card"><div className="section-heading"><div><div className="eyebrow">Known subscription</div><h3>Thao tác subscription đã biết</h3></div></div><div className="operation-tabs" role="tablist">{(['activate', 'change', 'cancel'] as Operation[]).map((item) => <button key={item} type="button" className={operation === item ? 'selected' : ''} onClick={() => setOperation(item)} role="tab" aria-selected={operation === item}>{item === 'activate' ? 'Activate' : item === 'change' ? 'Đổi package' : 'Cancel'}</button>)}</div>{operation === 'activate' && <ActivateForm onSuccess={handleResult} onError={notifyError} />}{operation === 'change' && <ChangePackageForm packages={packagesQuery.data ?? []} onSuccess={handleResult} onError={notifyError} />}{operation === 'cancel' && <CancelForm onSuccess={handleResult} onError={notifyError} />}</section></div>
    {result && <SubscriptionResult response={result} onActivate={handleResult} onError={notifyError} />}
  </>
}

type CreateValues = { restaurantId: string; packageCode: string; startAt: string; endAt: string; autoRenew: boolean; priceAmount: string; currencyCode: string }
function CreateSubscriptionForm({ packages, onSuccess, onError }: { packages: AdminPackageResponse[]; onSuccess: (response: SubscriptionResponse) => void; onError: (error: unknown) => void }) {
  const canManage = canManageRestaurantSubscriptions(useAuthStore((state) => state.user))
  const [initialTime] = useState(() => Date.now())
  const defaultPackage = packages.find((item) => item.active)
  const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<CreateValues>({ resolver: zodResolver(subscriptionSchema), defaultValues: { restaurantId: '', packageCode: defaultPackage?.code ?? '', startAt: toDateTimeLocal(new Date(initialTime).toISOString()), endAt: toDateTimeLocal(new Date(initialTime + 30 * 86400000).toISOString()), autoRenew: false, priceAmount: defaultPackage ? String(defaultPackage.priceAmount) : '', currencyCode: defaultPackage?.currencyCode ?? 'VND' } })
  const mutation = useMutation({ mutationFn: async (values: CreateValues) => { if (!canManage) throw new Error('FORBIDDEN'); const restaurantId = values.restaurantId.trim(); const restaurant = await restaurantsApi.getById(restaurantId); if (restaurant.packageAssignmentState === 'ACTIVE') throw new Error('SUBSCRIPTION_ALREADY_ACTIVE'); if (restaurant.packageAssignmentState === 'PENDING') throw new Error('SUBSCRIPTION_PENDING_EXISTS'); return adminSubscriptionsApi.create(restaurantId, { packageCode: values.packageCode, startAt: toUtcIso(values.startAt), endAt: toUtcIso(values.endAt), autoRenew: values.autoRenew, priceAmount: Number(values.priceAmount), currencyCode: values.currencyCode.trim().toUpperCase() }) }, onSuccess, onError: (error) => { const normalized = normalizeApiError(error); Object.entries(normalized.fieldErrors).forEach(([field, message]) => { if (field in { restaurantId: true, packageCode: true, startAt: true, endAt: true, priceAmount: true, currencyCode: true }) setError(field as keyof CreateValues, { message }) }); onError(error) } })
  return <form className="modal-form compact-form" onSubmit={(event) => void handleSubmit((values) => mutation.mutate(values))(event)} noValidate><div className="field"><label htmlFor="create-restaurant">Restaurant ID</label><input id="create-restaurant" {...register('restaurantId')} placeholder="UUID của nhà hàng" /><FieldError message={errors.restaurantId?.message} /></div><div className="field"><label htmlFor="create-package">Package active</label><select id="create-package" {...register('packageCode')}><option value="">Chọn package</option>{packages.filter((item) => item.active).map((item) => <option key={item.id} value={item.code}>{item.code} — {item.name}</option>)}</select><FieldError message={errors.packageCode?.message} /></div><div className="form-grid"><DateField id="create-start" label="Start (giờ local)" register={register('startAt')} error={errors.startAt?.message} /><DateField id="create-end" label="End (giờ local)" register={register('endAt')} error={errors.endAt?.message} /></div><div className="form-grid"><div className="field"><label htmlFor="create-price">Giá</label><input id="create-price" type="number" min="0" step="1" {...register('priceAmount')} /><FieldError message={errors.priceAmount?.message} /></div><div className="field"><label htmlFor="create-currency">Currency</label><input id="create-currency" maxLength={3} {...register('currencyCode')} /><FieldError message={errors.currencyCode?.message} /></div></div><label className="checkbox-field"><input type="checkbox" {...register('autoRenew')} /> Lưu auto renew (chưa phải thanh toán/gia hạn tự động)</label><p className="form-hint">startAt inclusive · endAt exclusive · Thời gian sẽ được chuyển sang ISO-8601 UTC.</p><button className="button button-primary" type="submit" disabled={isSubmitting || mutation.isPending}>{mutation.isPending ? 'Đang tạo…' : 'Tạo subscription'}</button></form>
}

function ActivateForm({ onSuccess, onError }: { onSuccess: (response: SubscriptionResponse) => void; onError: (error: unknown) => void }) {
  const canManage = canManageRestaurantSubscriptions(useAuthStore((state) => state.user))
  const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<{ restaurantId: string; subscriptionId: string }>({ resolver: zodResolver(subscriptionIdentifiersSchema) })
  const mutation = useMutation({ mutationFn: (values: { restaurantId: string; subscriptionId: string }) => { if (!canManage) return Promise.reject(new Error('FORBIDDEN')); if (!window.confirm('Activate sẽ tạo feature snapshot cho subscription. Bạn có muốn tiếp tục?')) return Promise.reject(new Error('CANCELLED')); return adminSubscriptionsApi.activate(values.restaurantId.trim(), values.subscriptionId.trim()) }, onSuccess, onError: (error) => { if (error instanceof Error && error.message === 'CANCELLED') return; const normalized = normalizeApiError(error); Object.entries(normalized.fieldErrors).forEach(([field, message]) => { if (field === 'restaurantId' || field === 'subscriptionId') setError(field, { message }) }); onError(error) } })
  return <IdentifierForm prefix="activate" register={register} errors={errors} isSubmitting={isSubmitting || mutation.isPending} submitLabel="Activate subscription" onSubmit={handleSubmit((values) => mutation.mutate(values))} />
}

type ChangeValues = { restaurantId: string; subscriptionId: string; packageCode: string; endAt: string; autoRenew: boolean; priceAmount: string; currencyCode: string }
function ChangePackageForm({ packages, onSuccess, onError }: { packages: AdminPackageResponse[]; onSuccess: (response: SubscriptionResponse) => void; onError: (error: unknown) => void }) {
  const canManage = canManageRestaurantSubscriptions(useAuthStore((state) => state.user))
  const [initialTime] = useState(() => Date.now())
  const defaultPackage = packages.find((item) => item.active)
  const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<ChangeValues>({ resolver: zodResolver(changePackageSchema), defaultValues: { packageCode: defaultPackage?.code ?? '', endAt: toDateTimeLocal(new Date(initialTime + 30 * 86400000).toISOString()), autoRenew: false, priceAmount: defaultPackage ? String(defaultPackage.priceAmount) : '', currencyCode: defaultPackage?.currencyCode ?? 'VND' } })
  const mutation = useMutation({ mutationFn: async (values: ChangeValues) => { if (!canManage) throw new Error('FORBIDDEN'); const restaurantId = values.restaurantId.trim(); const subscriptionId = values.subscriptionId.trim(); const current = await adminSubscriptionsApi.getById(restaurantId, subscriptionId); if (current.packageCode === values.packageCode) throw new Error('SAME_PACKAGE_CHANGE_NOT_ALLOWED'); if (!window.confirm('Gói hiện tại sẽ được kết thúc ngay lập tức. Hệ thống sẽ tạo subscription mới với mã khác; lịch sử cũ được giữ lại. Tiếp tục?')) throw new Error('CANCELLED'); return adminSubscriptionsApi.changePackage(restaurantId, subscriptionId, { packageCode: values.packageCode, endAt: toUtcIso(values.endAt), autoRenew: values.autoRenew, priceAmount: Number(values.priceAmount), currencyCode: values.currencyCode.trim().toUpperCase() }) }, onSuccess, onError: (error) => { if (error instanceof Error && error.message === 'CANCELLED') return; const normalized = normalizeApiError(error); if (normalized.code === 'SAME_PACKAGE_CHANGE_NOT_ALLOWED') setError('packageCode', { message: normalized.message }); Object.entries(normalized.fieldErrors).forEach(([field, message]) => { if (field in { restaurantId: true, subscriptionId: true, packageCode: true, endAt: true, priceAmount: true, currencyCode: true }) setError(field as keyof ChangeValues, { message }) }); onError(error) } })
  return <form className="modal-form compact-form" onSubmit={(event) => void handleSubmit((values) => mutation.mutate(values))(event)} noValidate><IdentifierFields prefix="change" register={register} errors={errors} /><div className="field"><label htmlFor="change-package">New package active</label><select id="change-package" {...register('packageCode')}><option value="">Chọn package</option>{packages.filter((item) => item.active).map((item) => <option key={item.id} value={item.code}>{item.code} — {item.name}</option>)}</select><FieldError message={errors.packageCode?.message} /></div><div className="field"><label htmlFor="change-end">End (giờ local)</label><input id="change-end" type="datetime-local" {...register('endAt')} /><FieldError message={errors.endAt?.message} /></div><div className="form-grid"><div className="field"><label htmlFor="change-price">Giá</label><input id="change-price" type="number" min="0" step="1" {...register('priceAmount')} /><FieldError message={errors.priceAmount?.message} /></div><div className="field"><label htmlFor="change-currency">Currency</label><input id="change-currency" maxLength={3} {...register('currencyCode')} /><FieldError message={errors.currencyCode?.message} /></div></div><label className="checkbox-field"><input type="checkbox" {...register('autoRenew')} /> Lưu auto renew (chưa phải thanh toán/gia hạn tự động)</label><button className="button button-primary" type="submit" disabled={isSubmitting || mutation.isPending}>{mutation.isPending ? 'Đang đổi package…' : 'Đổi package'}</button></form>
}

function CancelForm({ onSuccess, onError }: { onSuccess: (response: SubscriptionResponse) => void; onError: (error: unknown) => void }) {
  const canManage = canManageRestaurantSubscriptions(useAuthStore((state) => state.user))
  const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<{ restaurantId: string; subscriptionId: string }>({ resolver: zodResolver(subscriptionIdentifiersSchema) })
  const mutation = useMutation({ mutationFn: (values: { restaurantId: string; subscriptionId: string }) => { if (!canManage) return Promise.reject(new Error('FORBIDDEN')); if (!window.confirm('Cancel không xóa bản ghi nhưng kết thúc subscription. Bạn có muốn tiếp tục?')) return Promise.reject(new Error('CANCELLED')); return adminSubscriptionsApi.cancel(values.restaurantId.trim(), values.subscriptionId.trim()) }, onSuccess, onError: (error) => { if (error instanceof Error && error.message === 'CANCELLED') return; const normalized = normalizeApiError(error); Object.entries(normalized.fieldErrors).forEach(([field, message]) => { if (field === 'restaurantId' || field === 'subscriptionId') setError(field, { message }) }); onError(error) } })
  return <IdentifierForm prefix="cancel" register={register} errors={errors} isSubmitting={isSubmitting || mutation.isPending} submitLabel="Cancel subscription" onSubmit={handleSubmit((values) => mutation.mutate(values))} danger />
}

function IdentifierForm<T extends FieldValues & { restaurantId: string; subscriptionId: string }>({ prefix, register, errors, isSubmitting, submitLabel, onSubmit, danger = false }: { prefix: string; register: UseFormRegister<T>; errors: FieldErrors<T>; isSubmitting: boolean; submitLabel: string; onSubmit: FormEventHandler<HTMLFormElement>; danger?: boolean }) {
  return <form className="modal-form compact-form" onSubmit={onSubmit} noValidate><IdentifierFields prefix={prefix} register={register} errors={errors} /><button className={`button ${danger ? 'button-danger' : 'button-primary'}`} type="submit" disabled={isSubmitting}>{isSubmitting ? 'Đang xử lý…' : submitLabel}</button></form>
}

function IdentifierFields<T extends FieldValues & { restaurantId: string; subscriptionId: string }>({ prefix, register, errors }: { prefix: string; register: UseFormRegister<T>; errors: FieldErrors<T> }) { return <div className="form-grid"><div className="field"><label htmlFor={`${prefix}-restaurant`}>Restaurant ID</label><input id={`${prefix}-restaurant`} {...register('restaurantId' as Path<T>)} /><FieldError message={errors.restaurantId?.message?.toString()} /></div><div className="field"><label htmlFor={`${prefix}-subscription`}>Subscription ID</label><input id={`${prefix}-subscription`} {...register('subscriptionId' as Path<T>)} /><FieldError message={errors.subscriptionId?.message?.toString()} /></div></div> }
function DateField({ id, label, register, error }: { id: string; label: string; register: UseFormRegisterReturn; error?: string }) { return <div className="field"><label htmlFor={id}>{label}</label><input id={id} type="datetime-local" {...register} /><FieldError message={error} /></div> }

function SubscriptionResult({ response, onActivate, onError }: { response: SubscriptionResponse; onActivate: (response: SubscriptionResponse) => void; onError: (error: unknown) => void }) {
  const canManage = canManageRestaurantSubscriptions(useAuthStore((state) => state.user))
  const [copied, setCopied] = useState<string | null>(null)
  const activate = useMutation({ mutationFn: () => { if (!canManage) return Promise.reject(new Error('FORBIDDEN')); if (!window.confirm('Activate sẽ tạo feature snapshot cho subscription. Tiếp tục?')) return Promise.reject(new Error('CANCELLED')); return adminSubscriptionsApi.activate(response.restaurantId, response.id) }, onSuccess: onActivate, onError: (error) => { if (error instanceof Error && error.message === 'CANCELLED') return; onError(error) } })
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); setCopied(value) } catch { setCopied(null) } }
  return <section className="card detail-card result-card"><div className="section-heading"><div><div className="eyebrow">Mutation response</div><h3>Subscription vừa xử lý</h3></div>{response.status === 'PENDING' && <button className="button button-primary" type="button" disabled={activate.isPending} onClick={() => activate.mutate()}>{activate.isPending ? 'Đang activate…' : 'Activate ngay'}</button>}</div><div className="result-grid"><Fact label="Status" value={response.status} /><Fact label="Package" value={response.packageCode} /><Fact label="Giá" value={formatMoney(response.priceAmount, response.currencyCode)} /><Fact label="Auto renew" value={response.autoRenew ? 'Bật' : 'Tắt'} /><Fact label="Start" value={formatDateTime(response.startAt)} /><Fact label="End" value={formatDateTime(response.endAt)} /></div><div className="copy-row"><span><strong>Restaurant ID:</strong> <code>{response.restaurantId}</code></span><button className="button button-small button-ghost" type="button" onClick={() => void copy(response.restaurantId)}>Copy</button><span><strong>Subscription ID:</strong> <code>{response.id}</code></span><button className="button button-small button-ghost" type="button" onClick={() => void copy(response.id)}>Copy</button>{copied && <span className="muted">Đã copy</span>}</div><div className="snapshot"><strong>Feature snapshot ({response.features.length})</strong><pre>{JSON.stringify(response.features, null, 2)}</pre></div><p className="form-hint">Thời gian hiển thị theo timezone trình duyệt. ISO gốc: {response.startAt} → {response.endAt}. Auto renew chỉ là dữ liệu lưu trữ backend, chưa phải thanh toán/gia hạn tự động.</p></section>
}

function Fact({ label, value }: { label: string; value: string }) { return <div><span className="eyebrow">{label}</span><strong>{value}</strong></div> }

async function invalidateSubscriptionQueries(queryClient: ReturnType<typeof useQueryClient>, response: SubscriptionResponse) {
  await Promise.all([
    queryClient.invalidateQueries({ queryKey: ['admin', 'subscriptions'] }),
    queryClient.invalidateQueries({ queryKey: ['admin', 'restaurants'] }),
    queryClient.invalidateQueries({ queryKey: ['admin', 'dashboard'] }),
    queryClient.invalidateQueries({ queryKey: ['admin', 'restaurants', response.restaurantId, 'subscriptions'] }),
  ])
}
